global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "telemetry-api"
    static_configs:
      - targets: ["telemetry-api:8000"]   # use container name, not host.docker.internal